server:
  port: 8090
# Data Source
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/online_vehicle?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234567890
    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# App Properties
vehicle:
  app:
    jwtSecret: dilzSecretKey
    jwtExpirationMs: 86400000

#AWS Properties
amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIAW7E33XT3IHTNFIID
  secretKey: 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
  bucketName: dilz-vehicle-images